#!/bin/bash

#############################################################################
# raspberrypi-web-panel <https://github.com/pirafrank/raspberrypi-web-panel>
# A simple web panel to control your Raspberry Pi on a local network.
#
# Copyright (C) 2015 Francesco Pira <dev@fpira.com>
#
# This file is part of raspberrypi-web-panel
#
# raspberrypi-web-panel is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# raspberrypi-web-panel is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with raspberrypi-web-panel. If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

# tempF display rpi temp in Celsius
awk '{printf("%.1f &degC\n",$1/1e3)}' /sys/class/thermal/thermal_zone0/temp
